### PR TITLE
Added YETI Web Client.

### PR DESCRIPTION
**Pull request by jeffpuchalski**
I've added the code for the YETI Web Client browser-based graphical TAXII Client.

### CODE REVIEW

**Comment by gtback** [comment]
Though there are clear scenarios where this code would be used with the django-taxii-services or YETI code, in my opinion this code should probably be placed in a separate repository. TAXII clients and servers are different things, and though some software might try to serve both roles, keeping the code separate (though possibly both relying on something like libtaxii) helps prevent unneeded entanglement.

@MarkDavidson: what do you think?

**Comment by MarkDavidson** [comment]
@gtback, I see what you're saying. I'll have to think a little more before I have an opinion on where this code should ultimately reside (how's that for a non-answer?)

**Comment by gtback** [comment]
I created a [new repository](https://github.com/TAXIIProject/taxiiwebclient) for this code, so I'm going to close this.

**Comment by jeffpuchalski** [comment]
Thanks @gtback!

**Pull request closed without merging**
